<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2017-11-11T20:05:03</date>
  <millis>1510448703203</millis>
  <sequence>0</sequence>
  <logger>org.uma.jmetal.util.JMetalLogger</logger>
  <level>INFO</level>
  <class>org.uma.jmetal.util.JMetalLogger</class>
  <method>configureLoggers</method>
  <thread>1</thread>
  <message>Loggers configured with null</message>
</record>
<record>
  <date>2017-11-11T20:05:03</date>
  <millis>1510448703232</millis>
  <sequence>1</sequence>
  <logger>org.uma.jmetal.util.JMetalLogger</logger>
  <level>SEVERE</level>
  <class>org.uma.jmetal.util.JMetalException</class>
  <method>&lt;init&gt;</method>
  <thread>1</thread>
  <message>an exception was thrown during the call of newInstance()</message>
  <exception>
    <message>java.lang.reflect.InvocationTargetException</message>
    <frame>
      <class>sun.reflect.NativeConstructorAccessorImpl</class>
      <method>newInstance0</method>
    </frame>
    <frame>
      <class>sun.reflect.NativeConstructorAccessorImpl</class>
      <method>newInstance</method>
      <line>62</line>
    </frame>
    <frame>
      <class>sun.reflect.DelegatingConstructorAccessorImpl</class>
      <method>newInstance</method>
      <line>45</line>
    </frame>
    <frame>
      <class>java.lang.reflect.Constructor</class>
      <method>newInstance</method>
      <line>423</line>
    </frame>
    <frame>
      <class>org.uma.jmetal.util.ProblemUtils</class>
      <method>loadProblem</method>
      <line>23</line>
    </frame>
    <frame>
      <class>co.edu.unicauca.experiment.Experiment</class>
      <method>correr</method>
      <line>77</line>
    </frame>
    <frame>
      <class>co.edu.unicauca.experiment.Experiment</class>
      <method>main</method>
      <line>35</line>
    </frame>
  </exception>
</record>
